### ISSUE TITLE
Create Experiment Header Disappears and add numbers to questions

### ISSUE THREAD

**Issue by nerad25** [nerad25/Context-Experiment#24]
Title disappears when adding an item.

**Comment by nerad25** [comment]
Also number the questions!

**Comment by MMDimitri** [comment]
Spent about 2.5 hours attempting to add numbers to the items. So far, all I've accomplished is frustration and making the number that displays be the same number for each item (all of the numbers increment rather than just the most recent addition).

**Comment by colettejbeckwith** [comment]
completed the issue, items are now properly numbered and there is an option to delete specific items from the list

**Comment by colettejbeckwith** [comment]
issue completed. spent about 1.5 hours on messing around with it to finally get it working. Also added units to the data being captured.
