### ISSUE TITLE
Make rows clickable

### ISSUE THREAD

**Issue by nerad25** [nerad25/Context-Experiment#7]
make rows in manage experiment table clickable

**Comment by MMDimitri** [comment]
Spent about 4 hours trying several different ways of making rows clickable. Unfortunately, none of them worked. It'll be quick, I thought. It can't be that hard, I thought. There will be plenty of online tutorials, I thought. Nope. Nothing. None of them worked and I am too frustrated to continue searching at this point.

**Comment by nerad25** [comment]
Finished
